---
alias: Promise拒绝处理
---



### 全局的Promise拒绝处理

有关Promise的其中一个最具争议的问题是，如果在没有拒绝处理程序的情况下拒绝一个Promise，那么不会提示失败信息，这是JavaScript语言中唯一一处没有强制报错的地方.
Promise的特性决定了很难检测一个Promise是否被处理过

```javascript
let rejected = Promise.reject(42);

//此时,rejected还没有被处理

//过了一会
rejected.catch(function(value) {
  //现在rejected已经被处理
  console.log(value);
})
```

任何时候都可以调用then()方法或catch()方法，无论Promise是否已解决这两个方法都可以正常运行，但这样就很难知道一个Promise何时被处理。在此示例中，Promise被立即拒绝，但是稍后才被处理。

#### 4.1 Node.js

在Node.js中，处理Promise拒绝时会触发process对象上的两个事件：

* unhandledRejection 在一个事件循环中，当Promise被拒绝，并且没有提供拒绝处理程序时被调用。
* rejectionHandled      在一个事件循环后，当Promise被拒绝，并且没有提供拒绝处理程序时被调用

**unhandledRejection**

拒绝原因（通常是一个错误对象）及被拒绝的Promise作为参数被传入unhandledRejection事件处理程序中，以下代码展示了unhandledRejection的实际应用：

```javascript
let rejected;

process.on('unhandledRejection', function(reason, promise) {
  console.log(reason.message); //'Explosion'
  console.log(rejected === promise); //true
});

rejected = Promise.reject(new Error('Explosion'));
```

这个示例创建了一个已拒绝Promise和一个错误对象，并监听了unhandledRejection事件，事件处理程序分别接受错误对象和Promise作为它的两个参数。

**rejectionHandled**

rejectionHandled事件处理程序只有一个参数，也就是被拒绝的Promise

```javascript
let rejected;

process.on('rejectionHandled', function(promise) {
  console.log(rejected === promise); //true
});

rejected = Promise.reject(new Error('Explosion'));

//等待添加拒绝处理程序
setTimeout(() => {
  rejected.catch(function(value) {
    console.log(value.message); //Explosion
  })
},1000)
```

这里的rejectionHandled事件在拒绝处理程序最后被调用时触发，如果在创建rejected之后直接添加拒绝处理程序，那么rejectionHandled事件不会被触发，因为rejected创建的过程与拒绝处理程序的调用在同一个事件循环中，此时rejectionHandled事件尚未生效。

通过事件rejectionHandled和事件unhandledRejection将潜在未处理的拒绝存储为一个列表，等待一段时间后检查列表便能够正确地跟踪潜在的未处理拒绝。例如下面这个简单的未处理拒绝跟踪器

```javascript
let possiblyUnhandledRejections = new Map();

//如果一个拒绝没被处理,则将它添加到map集合中
process.on('unhandledRejection', function(reason, promise) {
  possiblyUnhandleRjections.set(promise, reason);
});

process.on('rejectionHandled', function(promise) {
  possiblyUnhandleRejections.delete(promise);
});

setInterval(function() {
  possiblyUnhandledRejections.forEach(function(reason, promise) {
    console.log(reason.message ? reason.message : reason);
    
    //做一些什么来处理这些拒绝
    handleRejection(promise, reason);
  });
  
  possiblyUnhandledRejections.clear();
}, 60000);
```

这段代码使用Map集合来存储Promise及其拒绝原因，每个Promise键都有一个拒绝原因的相关值。每当触发unhandledRejection事件时，会向Map集合中添加一组Promise及拒绝原因；每当触发rejectionHandled事件时，已处理的Promise会从Map集合中移除。结果是，possiblyUnhandledRejections会随着事件调用不断扩充或收缩。setInterval()调用会定期检查列表，将可能未处理的拒绝输出到控制台（实际上你会通过其他方式记录或者直接处理掉这个拒绝）。在这个示例中使用的是Map集合而不是WeakMap集合，这是因为你需要定期检查Map集合来确认一个Promise是否存在，而这是WeakMap无法实现的。



#### 4.2 浏览器

浏览器也是通过触发两个事件来识别未处理的拒绝的，虽然这些事件是在window对象上触发的，但实际上与Node.js中的完全等效。

* unhandledrejection　在一个事件循环中，当Promise被拒绝，并且没有提供拒绝处理程序时被调用。
* rejectionhandled　    在一个事件循环后，当Promise被拒绝，并且没有提供拒绝处理程序时被调用。

在Node.js实现中，事件处理程序接受多个独立参数；而在浏览器中，事件处理程序接受一个有以下属性的事件对象作为参数：

* type　事件名称（"unhandledrejection"或"rejectionhandled"）
* promise　被拒绝的Promise对象
* reason　来自Promise的拒绝值

浏览器实现中的另一处不同是，在两个事件中都可以使用拒绝值（reason），例如：

```javascript
let rejected;

window.onunhandledrejection = function(event) {
  console.log(event.type); //unhandledrejection
  console.log(event.reason.message); //Explosion
  console.log(rejected === event.promise); //true
}

window.onrejectionhandled = function(event) {
  console.log(event.type); //rejectionhandled
  console.log(event.reason.message); //Explosion
  console.log(rejected === event.promise); //true
}

rejected = Promise.reject(new Error('Explosion'));
```

这段代码用DOM 0级记法的onunhandledrejection和onrejectionhandled给两个事件处理程序赋值，如果你愿意的话也可以使用addEventListener("unhandledrejection")和addEventListener("rejectionhandled")，每个事件处理程序接受一个含有被拒绝Promise信息的事件对象，该对象的属性type、promise和reason在这两个事件处理程序中均可使用。在浏览器中，跟踪未处理拒绝的代码也与Node.js中的非常相似：

```javascript
//深入理解Es6 11.3章
```

